#MVP Pipeline CICD
---
trigger:
- master

pool:
  vmImage: ubuntu-20.04

variables:
- group: 'curlybytes-blog'
- name: phpVersion
  value: '7.4'

steps:
- task: Bash@3
  displayName: 'Use PHP version $(phpVersion)'
  inputs:
    targetType: 'inline'
    script: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Bash@3
  displayName: 'Use PHP version $(phpVersion)'
  inputs:
    targetType: 'inline'
    script: |
      CI_ENV="production" 
      php index.php Gitblog exportSite
    workingDirectory: '$(Build.SourcesDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/_site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
- task: AzureStaticWebApp@0
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)'
    app_location: '_site'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: '$(staticwebapptoken)'