###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
---
version: "3.1"
services:

    webserver:
        image: 'nginx:${NGINXVERSION}'
        container_name: ${APPNAME}_webserver
        working_dir: /application
        volumes:
            - '.:/application'
            - './scripts/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - ./app/logs/nginx:/var/logs/nginx
        ports:
            - '${WEBSERVERPORT}:80'


    php-fpm:
        container_name: ${APPNAME}_php
        build: scripts/phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './scripts/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

        environment:
            PHP_IDE_CONFIG: "serverName=Docker"   

    web:
        image: nginx:alpine
        ports:
        - "80:80"
        volumes:
        - ./_site:/usr/share/nginx/html